<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Home Page</title>
    </head>
    <body>
        <h1>Home Page</h1>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
            <a href="/logout">Logout</a>
        <?php else :?>
            <h2><a href="login">Login/Register</a></h2>
        <?php endif; ?>
    </body>
</html>
